Stockszilla/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quotes/', include('quotes.urls')),
    path('mutual.html',views.mutual),
    
]

urlpatterns += [
    path('portfolio', include('portfolio.urls', namespace='portfolio')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

portfolio/urls.py
from django.urls import path,include
from . import views

app_name="portfolio"
urlpatterns=[
path('buystocks<str:symbol>/',views.buy_stocks,name='buy_stocks'),
path('buy<str:symbol>/',views.buy,name='buy'),
path('buy<str:symbol>/<int:quantity>/',views.buy_share,name='buy_share'),
path('records/',views.transactions,name='transaction'),
path('transaction/<int:id>/',views.user_transaction,name='user_transaction'),
path('user_holdings/<str:symbol>/',views.user_holdings,name='user_holding'),
path('sell/<int:id>/',views.sell,name='sell'),
path('sell_stocks/<int:id>/',views.sell_stocks,name='sell_stocks'),
path('sell_share/<int:id>/<int:quantity>',views.sell_share,name='sell_share'),
path('holdings/',views.holdings,name='holding'),
path('leaderboard/',views.leaderboard,name='leaderboard'),
path('todays_report/',views.report,name='report'),
path('<str:symbol>/',views.cancel,name='cancel'),
]

urlpatterns+=[
path('quotes',include('quotes.urls')),
]

quotes/urls.py
from django.urls import path
from . import views


urlpatterns=[
path('',views.stocks,name='stocks'),
path('company/',views.company,name="company"),
path('company/<str:ticker>',views.graph,name="graph"),
path('<str:symbol>',views.company_stocks,name='company_stocks'),
path('Add_to_favourites/<str:symbol>',views.add_to_favourites,name='favourites'),
path('favourites/',views.fav,name='fav'),
]

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Transaction(models.Model):
	user = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
	company = models.CharField(max_length=100)
	price_per_share = models.DecimalField(max_digits=20,decimal_places=2)
	total_price = models.DecimalField(max_digits=20,decimal_places=2)
	action = models.CharField(max_length=5)
	gain_loss = models.CharField(max_length=5,null=True)
	amount = models.DecimalField(max_digits=20,decimal_places=2,null=True)
	b_balance = models.DecimalField(max_digits=20,decimal_places=2)
	a_balance = models.DecimalField(max_digits=20,decimal_places=2)
	symbol = models.CharField(max_length=10)
	quantity = models.IntegerField()
	date = models.DateField(auto_now=True)

class Holding(models.Model):
	user = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
	company = models.CharField(max_length=100)
	price_per_share = models.DecimalField(max_digits=20,decimal_places=2)
	total_price = models.DecimalField(max_digits=20,decimal_places=2)
	symbol = models.CharField(max_length=10)
	quantity = models.IntegerField()

portfolio/views.py
from django.shortcuts import render,redirect
import requests
import json
from accounts.models import Fund,Point
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Transaction,Holding
from quotes.views import company_stocks
from django.urls import reverse
from datetime import date

# Create your views here.
def buy_stocks(request,symbol):
	a=Fund.objects.get(user=request.user)
	money=a.funds
	api_req=requests.get("https://cloud.iexapis.com/stable/stock/"+ symbol + "/quote?token=pk_80042db83f9d49fc8195b96daf7a75ec")
	try:
		api=json.loads(api_req.content)
		
			
	except Exception as e:
		api="Error..."

	return render(request, 'buystocks.html', {'api':api,'money':money})

def buy(request,symbol):
	a=Fund.objects.get(user=request.user)
	money=a.funds
	q=request.POST.get('quantity')
	if (not q):
		q=0
	quantity=int(q)
	api_req=requests.get("https://cloud.iexapis.com/stable/stock/"+ symbol + "/quote?token=pk_80042db83f9d49fc8195b96daf7a75ec")
	try:
		api=json.loads(api_req.content)
		
			
	except Exception as e:
		api="Error..."

	if (api=="Error..."):
		price=0.0
		t_price=0.0
		c_balance=money

	else:
		price=api['latestPrice']
		t_price=quantity*price
		c_balance=float(money)-t_price

	

	if((quantity == 0) or (quantity < 0) or (c_balance < 0)):
		messages.error(request,'Enter valid no. of shares')
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	return render(request, 'buy.html', {'quantity':quantity,'price':price,'api':api,'t_price':t_price,'c_balance':c_balance,'money':money})
	
def transactions(request):
	a=Fund.objects.get(user=request.user)
	money = a.funds
	t = Transaction.objects.filter(user=request.user)
	if (t.exists()):
		b="1"
	else:
		b="0"
	return render(request, 'transactions.html', {'money':money,'b':b,'t':t})

def buy_share(request,symbol,quantity):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	api_req=requests.get("https://cloud.iexapis.com/stable/stock/"+ symbol + "/quote?token=pk_80042db83f9d49fc8195b96daf7a75ec")
	try:
		api=json.loads(api_req.content)
		
			
	except Exception as e:
		api="Error..."

	if (api=="Error..."):
		return buy_stocks(request,symbol)

	price=api['latestPrice']
	t_price=quantity*price
	c_balance=float(money)-t_price
	company=api['companyName']
	newtransaction=Transaction(user=request.user,company=company,price_per_share=price,total_price=t_price,action="bought",b_balance=money,a_balance=c_balance,symbol=symbol,quantity=quantity)
	newtransaction.save()
	newholding=Holding(user=request.user,company=company,price_per_share=price,total_price=t_price,symbol=symbol,quantity=quantity)
	newholding.save()
	a=Fund.objects.get(user=request.user)
	a.funds=c_balance
	a.save()
	return redirect('portfolio:transaction')

def cancel(request,symbol):
	return redirect(reverse('company_stocks',kwargs={'symbol':symbol}))

def user_transaction(request,id):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	t = Transaction.objects.get(id=id)
	return render(request,'user_transaction.html',{'money':money,'t':t})

def holdings(request):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	t = Holding.objects.filter(user=request.user)
	if (t.exists()):
		b="1"
	else:
		b="0"
	return render(request,'holdings.html',{'money':money,'t':t,'b':b})

def user_holdings(request,symbol):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	t = Holding.objects.filter(user=request.user,symbol=symbol)
	return render(request,'holdings.html',{'money':money,'t':t})

def sell(request,id):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	h=Holding.objects.get(id=id)
	api_req=requests.get("https://cloud.iexapis.com/stable/stock/"+ str(h.symbol) + "/quote?token=pk_80042db83f9d49fc8195b96daf7a75ec")
	try:
		api=json.loads(api_req.content)
		
	except Exception as e:
		api="Error..."
	if(api=="Error..."):
		price=0
	else:
		price=api['latestPrice']
	return render(request,'sell.html',{'h':h,'price':price,'api':api,'money':money})

def sell_stocks(request,id):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	q=request.POST.get('quantity')
	if (not q):
		q=0
	quantity=int(q)
	h=Holding.objects.get(id=id)
	api_req=requests.get("https://cloud.iexapis.com/stable/stock/"+ str(h.symbol) + "/quote?token=pk_80042db83f9d49fc8195b96daf7a75ec")
	try:
		api=json.loads(api_req.content)
		
			
	except Exception as e:
		api="Error..."

	if (api=="Error..."):
		price=0.0
		t_price=0.0
		c_balance=money
		g_l=""
		amt=0.0

	else:
		price=api['latestPrice']
		t_price=quantity*price
		c_balance=float(money)+t_price
		amt=t_price-float(h.price_per_share)*quantity
		if(amt < 0):
			amt=0-amt
			g_l="Loss"
		else:
			g_l="Profit"

	if((quantity == 0) or (quantity < 0) or (quantity > h.quantity)):
		messages.error(request,'Enter valid no. of shares')
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	return render(request,'sell_stocks.html',{'api':api,'money':money,'h':h,'quantity':quantity,'price':price,'t_price':t_price,'c_balance':c_balance,'amt':amt,'g_l':g_l})

def sell_share(request,id,quantity):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	h=Holding.objects.get(id=id)
	api_req=requests.get("https://cloud.iexapis.com/stable/stock/"+ str(h.symbol) + "/quote?token=pk_80042db83f9d49fc8195b96daf7a75ec")
	try:
		api=json.loads(api_req.content)
		
	except Exception as e:
		api="Error..."

	if (api=="Error..."):
		return buy_stocks(request,symbol)

	price=api['latestPrice']
	t_price=quantity*price
	c_balance=float(money)+t_price
	company=h.company
	amt=t_price-float(h.price_per_share)*quantity
	p = Point.objects.get(user=request.user)
	p.points = float(p.points)+(amt*0.1)
	p.save()
	if(amt < 0):
		amt=0-amt
		g_l="Loss"
	else:
		g_l="Profit"
	newtransaction=Transaction(user=request.user,company=company,price_per_share=price,total_price=t_price,action="sold",b_balance=money,a_balance=c_balance,symbol=h.symbol,quantity=quantity,amount=amt,gain_loss=g_l)
	newtransaction.save()
	if(quantity-h.quantity == 0):
		h.delete()
	else:
		h.quantity=h.quantity-quantity
		h.save()
	a=Fund.objects.get(user=request.user)
	a.funds=c_balance
	a.save()
	return redirect('portfolio:transaction')

def report(request):
	b=Fund.objects.get(user=request.user)
	money = b.funds
	g_l=0.0
	bought=0.0
	sold=0.0
	p_l="Profit"
	t = Transaction.objects.filter(user=request.user,date=date.today())
	if (t.exists()):
		a="1"
		for transaction in t:
			if (transaction.action == "sold"):
				sold=sold+float(transaction.total_price)
				if(transaction.gain_loss == "Profit"):
					g_l=g_l+float(transaction.amount)
				else:
					g_l=g_l-float(transaction.amount)
			else:
				bought=bought+float(transaction.total_price)
		if (g_l < 0.0):
			p_l="Loss"
			g_l=0-g_l
		else:
			p_l="Profit"
	else:
		a="0"
	return render(request,'report.html',{'b':b,'g_l':g_l,'bought':bought,'sold':sold,'a':a,'p_l':p_l,'t':t,'money':money})

def leaderboard(request):
	p=Point.objects.all().order_by('-points')
	return render(request,'leaderboard.html',{'p':p})




	   

portfolio/templates/buy.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>

{%if api%}
	{%if api == "Error..."%}
		{{api}}
	{% else %}

	<h1>{{api.companyName}}</h1>
	<br><br>
	Price (per share): ${{price}}<br><br>
	Quatity: {{quantity}}<br><br>
	Total price: ${{t_price}}<br><br>
	Balance (after transaction): ${{c_balance}}<br><br>
	<a id="buy" class="btn btn-dark" type="submit"  href="{% url 'portfolio:buy_share' symbol=api.symbol quantity=quantity %}" role="button" disabled>Buy</a>
	<a class="btn btn-dark" href="{% url 'portfolio:cancel' symbol=api.symbol %}" role="button">Cancel</a>
	<script>
		windows.onload=function(){
			document.getElementById("buy").disabled=false;
		}
	</script>

	{% endif %}
{% endif %}
<br><br>><br><br><br>
{% endblock %}

portfolio/templates/buystocks.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>
{%if api%}
	{%if api == "Error..."%}
		{{api}}
	{% else %}
	Company: {{api.companyName}}<br><br>
	Price (per share): ${{api.latestPrice}}<br><br>
	{% for message in messages %}
		<div class="alert alert-success">
			<a class="close" href="#" data-dismiss="alert">x</a>
			{{message}}
		</div>
	{% endfor %}
	No. of shares: <form class="form-inline my-2 my-lg-0" action="{% url 'portfolio:buy' symbol=api.symbol %}" class="search-form" method="POST">
		{% csrf_token %}
		<input class="form-control mr-sm-2" type="search" placeholder="quantity" aria-label="Search" name='quantity'>
		<button class="btn btn-dark btn-outline-success my-2 my-sm-0" type="submit">Proceed</button>
	  </form>
	  <br><br>
	  <a class="btn btn-dark" href="{% url 'portfolio:cancel' symbol=api.symbol %}" role="button">Cancel</a>
	
	{% endif %}
{% endif %}
<br><br>><br><br><br>
{% endblock %}

portfolio/templates/holdings.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>

{% if b == "0"%}
<br><br>
	<h1>No Holdings</h1>
<br><br>
{% else %}
	<br><br>
	<table class="table table-stripped table-bordered table-hover">
	  <thead class="thead-dark">
	    <tr>
	      <th scope="col">Id</th>
	      <th scope="col">Company</th>
	      <th scope="col">Price (per share)</th>
	      <th scope="col">No. of Shares</th>
	      <th scope="col">Total Worth</th>
	      <th scope="col"></th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for holding in t%}
	        <tr>
		      <th scope="row">{{holding.id}}</th>
		      <td><a href="{% url 'company_stocks' symbol=holding.symbol%}">{{holding.company}}</a></td>
		      <td>{{holding.price_per_share}}</td>
		      <td>{{holding.quantity}}</td>
		      <td>{{holding.total_price}}</td>
		      <td><a class="btn btn-info" href="{% url 'portfolio:sell' id=holding.id %}" role="button">Sell</a></td>
		    </tr>
		{% endfor %}
	  </tbody>
	</table>
{% endif %}
<br><br><br><br><br><br>
{% endblock %}

portfolio/templates/leaderboard.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Leaderboard</h1><br><br>

	
<table class="table table-stripped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">S. no.</th>
      <th scope="col">User</th>
      <th scope="col">Points</th>
    </tr>
  </thead>
  <tbody>
  	{% for points in p%}
        <tr>
	      <th scope="row">{{forloop.counter}}</th>
	      <td>{{points.user}}</a></td>
	      <td>{{points.points}}</td>
	    </tr>
  {% endfor %}
  </tbody>
</table>
<br><br>
{% endblock %}

portfolio/templates/report.html
{% extends 'base_layout.html' %}

{% block content %}

{% if a == "0"%}
<br><br><br><br>
<h1>No Transactions today</h1>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% else %}
	<br><br>
	<table class="table table-stripped table-bordered table-hover">
	  <thead class="thead-dark">
	    <tr>
	      <th scope="col">Transaction id</th>
	      <th scope="col">Company</th>
	      <th scope="col">Bought/Sold</th>
	      <th scope="col">Price (per share)</th>
	      <th scope="col">No. of Shares</th>
	      <th scope="col">Total price</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for transaction in t%}
	        <tr>
		      <th scope="row">{{transaction.id}}</th>
		      <td>{{transaction.company}}</td>
		      <td>{{transaction.action}}</td>
		      <td>{{transaction.price_per_share}}</td>
		      <td>{{transaction.quantity}}</td>
		      <td>{{transaction.total_price}}</td>
		    </tr>
		{% endfor %}
	  </tbody>
	</table><br><br>
	Worth of shares sold: ${{sold}}<br><br>
	Worth of shares bought: ${{bought}}<br><br>
	Total {{p_l}}: ${{g_l}}<br><br>
	Current balance: ${{money}}

	<br><br><br><br>

{% endif %}

{% endblock %}

portfolio/templates/sell.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>

Company: {{h.company}}<br><br>
Cost price (per share): ${{h.price_per_share}}<br><br>
No. of shares available: {{h.quantity}}<br><br>
Currect price: ${{price}}<br><br>
{% for message in messages %}
	<div class="alert alert-success">
		<a class="close" href="#" data-dismiss="alert">x</a>
		{{message}}
	</div>
{% endfor %}
No. of shares to be sold: <form class="form-inline my-2 my-lg-0" action="{% url 'portfolio:sell_stocks' id=h.id %}" class="search-form" method="POST">
	{% csrf_token %}
	<input class="form-control mr-sm-2" type="search" placeholder="quantity" aria-label="Search" name='quantity'>
	<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Proceed</button>
  </form>
  <br><br>
  <a class="btn btn-dark" href="{% url 'portfolio:cancel' symbol=h.symbol %}" role="button">Cancel</a>
  <br><br><br><br><br><br>
  {% endblock %}

portfolio/templates/sell_stocks.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>
{%if api%}
	{%if api == "Error..."%}
		{{api}}
	{% else %}

	Company: {{h.company}}<br><br>
	Cost price(per share): ${{h.price_per_share}}<br><br>
	Current price (per share): ${{price}}<br><br>
	Quatity: {{quantity}}<br><br>
	Total Selling price: ${{t_price}}<br><br>
	Balance (after transaction): ${{c_balance}}<br><br>
	{{g_l}}: ${{amt}}<br><br>
	<a id="Sell" class="btn btn-dark" href="{% url 'portfolio:sell_share' id=h.id quantity=quantity  %}" type="submit"  role="button" disabled>Sell</a>
	<a class="btn btn-dark" href="{% url 'portfolio:cancel' symbol=h.symbol %}" role="button">Cancel</a>
	{% endif %}
{% endif %}
<br><br><br><br><br><br>
{% endblock %}

portfolio/templates/transactions.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>

{% if b == "0"%}
<br><br><br><br>
	<h1>No Transactions today</h1>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% else %}
	<br><br>
	<table class="table table-stripped table-bordered table-hover">
	  <thead class="thead-dark">
	    <tr>
	      <th scope="col">Transaction id</th>
	      <th scope="col">Company</th>
	      <th scope="col">Bought/Sold</th>
	      <th scope="col">Price (per share)</th>
	      <th scope="col">No. of Shares</th>
	      <th scope="col">Total price</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for transaction in t%}
	        <tr>
		      <th scope="row">{{transaction.id}}</th>
		      <td><a href="{% url 'portfolio:user_transaction' id=transaction.id%}">{{transaction.company}}</a></td>
		      <td>{{transaction.action}}</td>
		      <td>{{transaction.price_per_share}}</td>
		      <td>{{transaction.quantity}}</td>
		      <td>{{transaction.total_price}}</td>
		    </tr>
		{% endfor %}
	  </tbody>
	</table>
{% endif %}
<br><br><br><br><br><br>
{% endblock %}

portfolio/templates/user_transaction.html
{% extends 'base_layout.html' %}

{% block content %}
<br><br>
<h1>Balance:${{money}}</h1><br><br>

Transaction id: {{t.id}}<br><br>
Company: {{t.company}}<br><br>
Bought/Sold: {{t.action}}<br><br>
Price (per share): ${{t.price_per_share}}<br><br>
No. of Shares: {{t.quantity}}<br><br>
Total Cost: ${{t.total_price}}<br><br>
Date: {{t.date}}<br><br>
Balance (befor transaction): ${{t.b_balance}}<br><br>
Balance (after transaction): ${{t.a_balance}}<br><br>
{% if t.action == "sold" %}
	{{t.gain_loss}}: ${{t.amount}}<br><br>
{% endif %}

<a class="btn btn-dark" href="{% url 'portfolio:transaction' %}" role="button">Back</a>
<br><br><br><br><br><br>
{% endblock %}