Stockszilla/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quotes/', include('quotes.urls')),
    path('mutual.html',views.mutual),
    
]

urlpatterns += [
    path('portfolio', include('portfolio.urls', namespace='portfolio')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from .import views
from .views import signup_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

portfolio/urls.py
from django.urls import path,include
from . import views

app_name="portfolio"
urlpatterns=[
path('buystocks<str:symbol>/',views.buy_stocks,name='buy_stocks'),
path('buy<str:symbol>/',views.buy,name='buy'),
path('buy<str:symbol>/<int:quantity>/',views.buy_share,name='buy_share'),
path('records/',views.transactions,name='transaction'),
path('transaction/<int:id>/',views.user_transaction,name='user_transaction'),
path('user_holdings/<str:symbol>/',views.user_holdings,name='user_holding'),
path('sell/<int:id>/',views.sell,name='sell'),
path('sell_stocks/<int:id>/',views.sell_stocks,name='sell_stocks'),
path('sell_share/<int:id>/<int:quantity>',views.sell_share,name='sell_share'),
path('holdings/',views.holdings,name='holding'),
path('leaderboard/',views.leaderboard,name='leaderboard'),
path('todays_report/',views.report,name='report'),
path('<str:symbol>/',views.cancel,name='cancel'),
]

urlpatterns+=[
path('quotes',include('quotes.urls')),
]

quotes/urls.py
from django.urls import path
from . import views


urlpatterns=[
path('',views.stocks,name='stocks'),
path('company/',views.company,name="company"),
path('company/<str:ticker>',views.graph,name="graph"),
path('<str:symbol>',views.company_stocks,name='company_stocks'),
path('Add_to_favourites/<str:symbol>',views.add_to_favourites,name='favourites'),
path('favourites/',views.fav,name='fav'),
]

templates/base_layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
      footer a{ color: #ffffff;}
      footer a:hover{ color: #ffffff;}
    </style>
    <title>Financers</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Financers</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'stocks' %}">Company Stocks<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'fav' %}">Favourites<span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:transaction' %}">Transactions</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:holding' %}">Holdings</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:report' %}">Today's Report</a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:leaderboard' %}">Leaderboard</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'stocks' %}">
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button class="float-right bg-dark text-white" type="submit" style="position: absolute; right: 0;">Logout</button>
            </form>
            <span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <footer class="bg-dark text-white">
    <div class="container py-3">
        <div class="col-lg-6 col-sm-6 pb-2">
          <h4>Contact Us</h4>
          <p>
            <strong>Phone:</strong> +91-1000000000<br>
            <strong>Email:</strong><a href="#">help@financers.com</a><br>
          </p>
        </div>
        <div class="text-center">Developed by Financers Team</div> 
    </div>
    <div class="container-fluid text-center bg-secondary py-2">
      &copy; 2022. All rights are reserved.
    </div>
  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/homepage.html
{% load static %}

<!-------

<h1 class="display-1 font-weight-bold text-responsive" style="color:#1C2833">STOCKSZILLA</h1>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/media/pexels-david-mcbee-730564.jpg" width="50%" height="500px" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/media/pexels-energepiccom-159888.jpg" width="50%" height="500px" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/media/pexels-lukas-669610.jpg" width="50%" height="500px" alt="Third slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/media/pexels-timur-saglambilek-185576.jpg" height="500px" width="50%" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br><br>
  <blockquote class="blockquote text-center">
    <p class="mb-0">Your one stop solution for stock market and place to build your stock portfolio even before investing!</p>
  </blockquote>
  <br>
<h1 class="font-weight-bold">About Us!</h1>
<blockquote class="blockquote text-justify">
    <p class="mb-0">Stockszilla is a Virtual Stock Market Website which uses accurate and real-time stock market data to paint the picture of investment portfolio for prospective investors. Interested traders can sign up on our website for free and practice trading using Virtual Money!
        You can search tickers for any stock and view its current and past performance visually. You can also buy and sell stocks using virtual money and build up your experience in this field! You can also build up a portfolio for yourself!</p>
  </blockquote>
  <br><br><br><br><br>-------->
  <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Homepage</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Financers</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'accounts:login' %}" hidden>Login</a>
                {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Features
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'stocks' %}">Stock</a></li>
                  <li><a class="dropdown-item" href="./mutual.html">Mutual Funds</a></li>
                  
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- End Of Nav -->
  <!--carousel-->
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://source.unsplash.com/1600x480/?stock market" class="d-block w-100">
        <div class="carousel-caption d-none d-md-block">
          <h5>-Phillip Fisher</h5>
          <p>“The stock market is filled with individuals who know the price of everything, but the value of nothing.”</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/1600x480/?mutual funds" class="d-block w-100">
        <div class="carousel-caption d-none d-md-block">
          <h5> ― Jim Cramer</h5>
          <p>“Every once in a while, the market does something so stupid it takes your breath away.” </p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/1600x480/?investment" class="d-block w-100">
        <div class="carousel-caption d-none d-md-block">
          <h5> ― Robert Arnot
          <p>“In investing, what is comfortable is rarely profitable.” </p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <!-------End of carousel--->
  <!--------Boxes-->
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body"style="margin-top: 15px;">
          <h5 class="card-title">Stock Market</h5>
          <p class="card-text">You can trade here with dummy Money</p>
          <a href="{% url 'stocks' %}" class="btn btn-primary">Click Here</a>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body"style="margin-top: 15px;">
          <h5 class="card-title">Mutual Funds</h5>
          <p class="card-text">Only Information Regarding Mutual Funds</p>
          <a href="./mutual.html" class="btn btn-primary">Click Here</a>
        </div>
      </div>
    </div>
  </div>
  <!---End of boxes-->



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

   
  </body>
</html>

templates/mutual.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>MutualFunds</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Financers</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="./Homepage.html">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'stocks' %}">Stock</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- End Of Nav -->
<!---blog kinds feature for mutaul ----------->
<h3 class="card-title">Understanding The Various Types of Mutual Funds</h3>
<div class="card mb-3">
    <img src="https://source.unsplash.com/1600x350/?money" class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text">Mutual funds offer an opportunity to invest across different asset classes based on your financial goals, risk profile and investment horizon. Be it a seasoned investor or a budding investor, anyone can invest in mutual funds to grow wealth. However, in order to make an informed decision, it is necessary to know the various types of mutual funds available for investing.
        Broadly, mutual funds are divided into three categories i.e. equity funds, debt funds, and hybrid funds. Let’s gain a deeper understanding of each one of these.</p>
        <h4 class="card-title">1.Equity Funds or Growth Funds:</h4>
        <p class="card-text">
          <ul>
            <li>Large Cap Funds generate relatively stable returns by investing in stocks of well-established companies. Small Cap Funds and Mid Cap Funds, on the other hand, are high-risk high-return funds that invest in stocks of small-sized and mid-sized companies respectively.</li>
            <li>Highly aggressive investors may invest in Focused Funds which maintain a portfolio of highly promising stocks to deliver outstanding returns.</li>
            <li>ELSS Funds enable tax-saving of up to Rs 1.5 lakh under Section 80C of the Income Tax Act along with long term wealth accumulation.</li>
          </ul>
        </p>
        <h4 class="card-title">2.Debt Funds or Income Funds:</h4>
        <p class="card-text">These funds invest in interest generating securities like treasury bills, government securities and bonds. They aim to preserve the capital and generating a regular income on investment. These funds are comparatively safer than equity funds. As compared to traditional bank FDs, debt funds are better avenues to grow wealth over medium to long term. There are different kinds of debt funds available for different financial goals as follows:
          <ul>
            <li>Duration based funds beginning from Overnight Funds to Long Duration Funds invest in debt securities which mature at different dates. You may invest in them as per your investment horizon.</li>
            <li>Liquid Funds provides you instant access to cash during emergencies.</li>
            <li>Aggressive investors may allocate a part of their portfolio towards Credit Risk Funds which invest in risky corporate bonds.</li>
            <li>Gilt Funds invest in government securities having different maturity dates to generate optimal returns on investment.</li>
            <li>Dynamic Bond Funds are all-season funds to grow wealth by taking advantage of interest rate movements.</li>
          </ul>
        </p>
        <h4 class="card-title">3.Hybrid Funds:</h4>
        <p class="card-text">
          <ul>
          <li>Conservative/Balanced/Aggressive Hybrid Funds invest in a blend of stocks and bonds to generate optimal returns.</li>
          <li>Multi Asset Allocation Funds invest in a portfolio which is made up of multiple asset classes like stocks, bonds and gold.</li>
          <li>Hybrid Funds may be suitable for retirees who want to beat inflation and earn higher returns on their retirement corpus.</li>
          <li>Arbitrage Funds generate gains by using the price differential of an asset (like stocks) in the cash and derivatives market.</li>
          <li>Equity Savings Fund invest in stocks, debt securities and utilize arbitrage opportunities to accumulate wealth.</li>
        </ul>
        </p>
        <h4 class="card-title">The Final Takeaway</h4>
        <p class="card-text">Investing in mutual funds is a smart way to earn a higher return on investment. However, 
          choosing the right fund can become a task sometimes. To kick start your investment journey, you can explore the Investment 
          Packs on Paytm Money app. These well-diversified 
          packs are designed to suit your risk profile and may cater to your investment needs.</p>

    </div>
  </div>
  


  
  


 <!-- End of blog -->